imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: doctrine_extensions.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'fields.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
        types:
            phone_number: Misd\PhoneNumberBundle\Doctrine\DBAL\Types\PhoneNumberType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        # for gedmo/doctrine-extensions
        mappings:
            translatable:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Translatable\Entity
                # make sure vendor library location is correct
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
            loggable:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
            tree:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    profile:
        form:
            type: AppBundle\Form\Type\ProfileFormType

oneup_flysystem:
    adapters:
        users_adapter:
            local:
                directory: %kernel.root_dir%/../web/uploads/users/images
        contract_attachments:
            local:
                directory: %kernel.root_dir%/../web/uploads/contracts/attachments
        offer_summaries:
            local:
                directory: %kernel.root_dir%/../web/uploads/offers
        pay_attachments:
            local:
                directory: %kernel.root_dir%/../web/uploads/pay_attachments
    filesystems:
        users_images_fs:
            adapter: users_adapter
            mount: users_images_fs
        contract_attachments_fs:
            adapter: contract_attachments
            mount: contract_attachments_fs
        offer_summaries_fs:
            adapter: offer_summaries
            mount: offer_summaries_fs
        pay_attachments_fs:
            adapter: pay_attachments
            mount: pay_attachments_fs

vich_uploader:
    db_driver:  orm
    storage:    flysystem
    mappings:
        users_images:
            uri_prefix:         /uploads/users/images
            upload_destination: users_images_fs
            namer:              vich_uploader.namer_uniqid
        contract_attachments:
            uri_prefix:         /uploads/contracts/attachments
            upload_destination: contract_attachments_fs
            namer:              vich_uploader.namer_uniqid
        offer_summaries:
            uri_prefix:         /uploads/offers
            upload_destination: offer_summaries_fs
            namer:              vich_uploader.namer_uniqid
        pay_attachments:
            uri_prefix:         /uploads/pay_attachments
            upload_destination: pay_attachments_fs
            namer:              vich_uploader.namer_uniqid

assetic:
    debug:              false
    use_controller:     %kernel.debug%
    filters:
        cssrewrite:     ~
        jsqueeze:   ~
        scssphp:
            formatter: 'Leafo\ScssPhp\Formatter\Compressed'
